import Head from 'next/head'
import Link from 'next/link'
import ReactFullpage from "@fullpage/react-fullpage"
import { useState } from 'react'
import { Menu } from '../src/components/Menu'


const originalColors = ['#0063C3','#0063C3','#0063C3','#0063C3'];

export default function Home() {

  const [state, setState ] = useState({
    sectionsColor: [...originalColors],
    fullpages: [
      {
        animateAnchor: true,
        anchors:['home', 'servicios','procesos','contacto'],
      },
      // {
      //   text: "Section 2"
      // },
      // {
      //   text: 'Section 3',
      // },
      // {
      //   text: 'Section 4',
      // }
    ]
  })
  const onLeave = (origin, destination, direction) => {
    console.log("onLeave", { origin, destination, direction });

  }
  const handleChangeColors = () => {
    // const newColors =  state.sectionsColor[0] == "yellow" ? [...originalColors] : ['yellow', 'blue', 'white']
    setState({...state, sectionsColor: newColors })
  }
  const handleAddSection = () => {
    setState( state => {
      const { fullpages } = pages
      const { length } = fullpages 
      fullpages.push({
        text: `section ${length + 1}`,
        id: Math.random()
      })
      return {
        fullpages: [...fullpages]
      }
    })
  }
  const handleRemovesection = () => {
    setState( state => {
      const { fullpages } = state
      const newPAges = [...fullpages]
      newPages.pop()

      return { fullpages: newPages }
    })
  }

  const { fullpages } = state 
  if(!fullpages.length){
    return null
  }


  return (
    
   

    <>
      <Head>
        <title>Imperio del Sol</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Menu/> */}
      <ReactFullpage
        licenseKey = {''}
        navigation
        onLeave={ onLeave }
        sectionsColor={state.sectionsColor}
        render={comp =>
          console.log("render prop change 1") || (
            <ReactFullpage.Wrapper>

              <div className="section">
                <div className="home">
                  <img src="./imperiodelsol.svg" alt="" />

                </div>
              </div>
              <div className="section">
                <div className="lineas">
                  <div className="lineas__santaclara">
                    <h1>Santa Clara</h1>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi, repellat.</p>
                  
                      <a href="#contacto" className="btn__imperio">Saber más</a>
                    
                  </div>
                  <div className="lineas__lidertex">
                    <h1>LIDERTEX</h1>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste quis aliquam eaque eos nihil.</p>
                    <a href="#contacto" className="btn__imperio">Saber más</a>
                  </div>
                </div>
              </div>
              <div className="section">
                <div className="procesos">
                  <h1 className="procesos__title">Procesos</h1>
                  <div className="procesos__box">
                    <div className="procesos__item">
                      <img src="/ico/fibra.png" alt="" />
                      <h5>Fibras</h5>
                    </div>
                    <div className="procesos__item">
                      <img src="/ico/hilado.png" alt="" />
                      <h5>Hilado</h5>
                    </div>
                    <div className="procesos__item">
                      <img src="/ico/tejido_punto.png" alt="" />
                      <h5>Tejido de punto</h5>
                    </div>
                    <div className="procesos__item">
                      <img src="/ico/casa_tinte.png" alt="" />
                      <h5>Casa de tinte</h5>
                    </div>
                    <div className="procesos__item">
                      <img src="/ico/impresion_cobertura.png" alt="" />
                      <h5>Impresión de cobertura completa</h5>
                    </div>
                    <div className="procesos__item">
                      <img src="/ico/corte.png" alt="" />
                      <h5>Corte</h5>
                    </div>
                    <div className="procesos__item">
                      <img src="/ico/costura.png" alt="" />
                      <h5>Costura</h5>
                    </div>
                    <div className="procesos__item">
                      <img src="/ico/bordado.png" alt="" />
                      <h5>Estampado y bordado</h5>
                    </div>
                    <div className="procesos__item">
                      <img src="/ico/calidad.png" alt="" />
                      <h5>Control de calidad</h5>
                    </div>
                    <div className="procesos__item">
                      <img src="/ico/planchado.png" alt="" />
                      <h5>Planchado y embalaje</h5>
                    </div>
                  </div>
                </div>
              </div>
              <div className="section" data-anchor="contacto">
                <div className="contacto">
                  <h1 className="contacto__title">Contactanos</h1>
                  <div className="contacto__form">
                    <input type="text" placeholder="Nombre y Apellidos"/>
                    <input type="text" placeholder="Teléfono / Celular"/>
                    <input type="text" placeholder="Correo"/>
                    <textarea name="" id="" cols="30" rows="10" placeholder="Escriba su mensaje "></textarea>
                    <button type="submit">Enviar</button>
                  </div>
                </div>
              
              </div>

              
             
            </ReactFullpage.Wrapper>
          )
        }
      />

      
    </>
  )
}

